DROP TABLE IF EXISTS RESTAURANTS_PHOTOS;
DROP TABLE IF EXISTS USERS_PREFERENCES;
DROP TABLE IF EXISTS RESTAURANTS_PREFERENCES;
DROP TABLE IF EXISTS USER_RATINGS;
DROP TABLE IF EXISTS PREFERENCES;
DROP TABLE IF EXISTS PHOTOS;
DROP TABLE IF EXISTS TAGS;
DROP TABLE IF EXISTS RESTAURANTS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE IF NOT EXISTS USERS(
       USER_ID INT NOT NULL AUTO_INCREMENT,
       USER_NAME VARCHAR(255) NOT NULL,
       PWD VARCHAR(255) NOT NULL,
       EMAIL VARCHAR(255) NOT NULL,
       VERIFIED INT NOT NULL,
       PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS RESTAURANTS(
       RESTAURANT_ID INT NOT NULL AUTO_INCREMENT,
       RESTAURANT_NAME VARCHAR(255) NOT NULL,
       LOCATION VARCHAR(255) NOT NULL,
       PRIMARY KEY (RESTAURANT_ID)
);

CREATE TABLE IF NOT EXISTS TAGS(
       TAG_ID INT NOT NULL AUTO_INCREMENT,
       CONTENT VARCHAR(255) NOT NULL,
       PRIMARY KEY (TAG_ID)
);

CREATE TABLE IF NOT EXISTS PHOTOS(
       PHOTO_ID INT NOT NULL AUTO_INCREMENT,
       INFORMATION VARCHAR(255) NOT NULL,
       LIKE_ INT,
       URL VARCHAR(255) NOT NULL,
       TAG_ID INT,
       USER_ID INT,
       PRIMARY KEY (PHOTO_ID),
       FOREIGN KEY (TAG_ID) REFERENCES TAGS(TAG_ID),
       FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE IF NOT EXISTS PREFERENCES(
       PREFERENCE_ID INT NOT NULL AUTO_INCREMENT,
       PREFERENCE VARCHAR(255) NOT NULL,
       PRIMARY KEY (PREFERENCE_ID)
);
CREATE TABLE IF NOT EXISTS USER_RATINGS(
       USER_ID INT NOT NULL,
       RESTAURANT_ID INT NOT NULL,
       RATING INT NOT NULL,
       PRIMARY KEY (USER_ID,RESTAURANT_ID),
       FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
       FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID)
);
CREATE TABLE IF NOT EXISTS RESTAURANTS_PHOTOS(
       PHOTO_ID INT NOT NULL,
       RESTAURANT_ID INT NOT NULL,
       PRIMARY KEY (PHOTO_ID,RESTAURANT_ID),
       FOREIGN KEY (PHOTO_ID) REFERENCES PHOTOS(PHOTO_ID),
       FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID)
);
CREATE TABLE IF NOT EXISTS USERS_PREFERENCES(
       USER_ID INT NOT NULL,
       PREFERENCE_ID INT NOT NULL,
       PRIMARY KEY (USER_ID,PREFERENCE_ID),
       FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
       FOREIGN KEY (PREFERENCE_ID) REFERENCES PREFERENCES(PREFERENCE_ID)      
);
CREATE TABLE IF NOT EXISTS RESTAURANTS_PREFERENCES(
       RESTAURANT_ID INT NOT NULL,
       PREFERENCE_ID INT NOT NULL,
       PRIMARY KEY (RESTAURANT_ID,PREFERENCE_ID),
       FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID),
       FOREIGN KEY (PREFERENCE_ID) REFERENCES PREFERENCES(PREFERENCE_ID)       
);


