/*userdata*/
INSERT INTO USERS (USER_NAME,PWD,EMAIL,VERIFIED) VALUES ('a','123','a@gmail.com',0);
INSERT INTO USERS (USER_NAME,PWD,EMAIL,VERIFIED) VALUES ('b','321','b@gmail.com',0);
INSERT INTO USERS (USER_NAME,PWD,EMAIL,VERIFIED) VALUES ('C','221','c@gmail.com',0);

/*restaurants data*/
INSERT INTO RESTAURANTS (RESTAURANT_NAME,LOCATION,OPENING_HOUR) VALUES ('Subway','Upper Campus Morven Brown Building C20','M-T, 7.30am-9.30pm. F, 7.30am-8.30pm S-S, 10am-5.15pm');
INSERT INTO RESTAURANTS (RESTAURANT_NAME,LOCATION,OPENING_HOUR) VALUES ('Max Brenner','Lower Campus University Terrace B8','M-Th, 8am-10.30pm, F 8am-midnight, 
Sat, 10am-midnight, Sun, 10am-10.30pm');
INSERT INTO RESTAURANTS (RESTAURANT_NAME,LOCATION,OPENING_HOUR) VALUES ('Bar Navitas','Lower Campus Tyree Energy Technologies Building H6', 'Semester: M-F, 7am-5pm Sat, 8am-3pm 
Semester break: M-F, 7am-3pm, Sat 8am-3pm');
INSERT INTO RESTAURANTS (RESTAURANT_NAME,LOCATION,OPENING_HOUR) VALUES ('Library Lawn Coffee Cart','Upper Campus Library Lawn F21','M-F, 7.30am-5pm');
INSERT INTO RESTAURANTS (RESTAURANT_NAME,LOCATION,OPENING_HOUR) VALUES ('Southern Wok','Upper Campus Morven Brown Building C20','Semester: M-T, 9am-6pm. F, 9am-4pm 
Semester break: M-F, 9am-4pm'); /*5*/
INSERT INTO RESTAURANTS (RESTAURANT_NAME,LOCATION,OPENING_HOUR) VALUES ('Satay Delight','Upper Campus Mathews Arcade F23','Semester: M-F, 8.3am0-6.30pm
Semester break: M-F, 8.30am-6pm');
INSERT INTO RESTAURANTS (RESTAURANT_NAME,LOCATION,OPENING_HOUR) VALUES ('Biblio','Upper Campus under Mathews Theatres F23','Semester: M-F, 7am-6pm 
Semester break: M-F, 7am-4pm');
INSERT INTO RESTAURANTS (RESTAURANT_NAME,LOCATION,OPENING_HOUR) VALUES ('Boost Juice','Upper Campus Morven Brown Building C20','M-F, 8am-6pm');
INSERT INTO RESTAURANTS (RESTAURANT_NAME,LOCATION,OPENING_HOUR) VALUES ('Bun Me','Lower Campus University Terraces B8','Hours: M-F 10.30am-8pm, Sat 10.30am-5.30pm');
INSERT INTO RESTAURANTS (RESTAURANT_NAME,LOCATION,OPENING_HOUR) VALUES ('Classic Kebab','Upper Campus Mathews Arcade F23','Semester: M-F, 7am-6.30pm 
Semester break: M-F, 7am-5pm'); /*10*/
INSERT INTO RESTAURANTS (RESTAURANT_NAME,LOCATION,OPENING_HOUR) VALUES ('Coco Cubano','Lower Campus University Terraces B8','M-F, 7.30am-10pm, Th-Sat, 7.30am-Midnight, Sun, 7.30am-10pm'); 
INSERT INTO RESTAURANTS (RESTAURANT_NAME,LOCATION,OPENING_HOUR) VALUES ('Guzman Y Gomez','Lower Campus University Terraces B8','M-Sun, 10am-10pm'); 
INSERT INTO RESTAURANTS (RESTAURANT_NAME,LOCATION,OPENING_HOUR) VALUES ('Jewel of India','Upper Campus Mathews Arcade F23','Semester: M-F, 9am-6pm 
Semester break: M-F, 10am-4pm'); 
INSERT INTO RESTAURANTS (RESTAURANT_NAME,LOCATION,OPENING_HOUR) VALUES ('Mamak Village','Lower Campus University Terraces B8','M-Sat, 8am-10pm');  
INSERT INTO RESTAURANTS (RESTAURANT_NAME,LOCATION,OPENING_HOUR) VALUES ('Q Lounge','Middle Campus Quadrangle Building E15','Semester: M-F, 5.30am-6.30pm
Semester break: M-F, 7am-4pm');/*15*/
INSERT INTO RESTAURANTS (RESTAURANT_NAME,LOCATION,OPENING_HOUR) VALUES ('Yummba','Lower Campus University Terraces B8','M-F, 8am-7:30pm, S, 10am-6pm');
/*INSERT INTO RESTAURANTS (RESTAURANT_NAME,LOCATION) VALUES ('Max Brenner','Lower Campus University Terraces');
INSERT INTO RESTAURANTS (RESTAURANT_NAME,LOCATION) VALUES ('Max Brenner','Lower Campus University Terraces');
INSERT INTO RESTAURANTS (RESTAURANT_NAME,LOCATION) VALUES ('Max Brenner','Lower Campus University Terraces');/*20*/


/*food tag*/
INSERT INTO TAGS (CONTENT) VALUES ('Sandwich');
INSERT INTO TAGS (CONTENT) VALUES ('Rice');
INSERT INTO TAGS (CONTENT) VALUES ('Pizza');
INSERT INTO TAGS (CONTENT) VALUES ('Burger');
INSERT INTO TAGS (CONTENT) VALUES ('Lasagna');/*5*/
INSERT INTO TAGS (CONTENT) VALUES ('Coffee');
INSERT INTO TAGS (CONTENT) VALUES ('Stir fried');
INSERT INTO TAGS (CONTENT) VALUES ('Laksa');
INSERT INTO TAGS (CONTENT) VALUES ('Environment');
INSERT INTO TAGS (CONTENT) VALUES ('Juice');/*10*/
INSERT INTO TAGS (CONTENT) VALUES ('Bun');
INSERT INTO TAGS (CONTENT) VALUES ('Gozleme');
INSERT INTO TAGS (CONTENT) VALUES ('Kebab');
INSERT INTO TAGS (CONTENT) VALUES ('Steak');
INSERT INTO TAGS (CONTENT) VALUES ('Salad');/*15*/
INSERT INTO TAGS (CONTENT) VALUES ('Chimichangas');
INSERT INTO TAGS (CONTENT) VALUES ('Malay');
INSERT INTO TAGS (CONTENT) VALUES ('Icecream');
INSERT INTO TAGS (CONTENT) VALUES ('MilkShake');
INSERT INTO TAGS (CONTENT) VALUES ('Sausages');/*20*/
INSERT INTO TAGS (CONTENT) VALUES ('Pork');
INSERT INTO TAGS (CONTENT) VALUES ('Falafels');
INSERT INTO TAGS (CONTENT) VALUES ('waffles');
INSERT INTO TAGS (CONTENT) VALUES ('pancakes');
INSERT INTO TAGS (CONTENT) VALUES ('chocolate');/*25*/

/*photos*/
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Subway from outside.',0,'img/Subway UNSW/on-the-right-as-you-walk-down-from-the-library-57009.jpg',9,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Max Brenner from outside.',0,'img/Max Brenner/from-the-courtyard-in-the-middle-of-university-terraces-59951.jpg',9,2);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Max Brenner chocolate',0,'img/Max Brenner/max-brenner-chocolate.jpg',23,3);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Max Brenner waffles',0,'img/Max Brenner/max-brenner-waffles.jpg',23,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('pesto vegetarian pizza',0,'img/Bar Navitas/pesto-vegetarian-pizza.jpg',3,1);/*5*/
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('beef Lasagna',0,'img/Bar Navitas/Beef-Lasagna.jpg',5,2);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Navita special burger!',0,'img/Bar Navitas/Navita-Burgers.jpg',4,3);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Library Lawn Coffee guys',0,'img/Library Lawn coffee cart/Library-coffee-cart-1.jpg',9,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('stir fried goodies',0,'img/southern wok/Southern-wok-1.jpg',7,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('stir fried goodies number 2',0,'img/southern wok/southern-wok-2.jpg',7,1);/*10*/
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Chicken Laksa',0,'img/Asian Delight/Chicken Laksa.JPG',8,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Soy Chicken Laksa',0,'img/Asian Delight/Soy Chicken Laksa.jpg',8,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Satay delight outside view',0,'img/Asian Delight/__a-satay_delight1.jpg',9,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Biblio from outside',0,'img/Biblio/1-1807.jpg',9,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Boost juice',0,'img/Boost Juice/10362192_644909445599700_1308718797_a.jpg',10,1);/*15*/
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Bun Me environment',0,'img/Bun Me/10247201_388666201275241_8654907787134843112_n.jpg',9,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Classic Kebab from outside',0,'img/Classic Kebab/1-1813.jpg',9,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Classic Kebab Bun',0,'img/Classic Kebab/Bun.jpg',11,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Classic Kebab gozleme',0,'img/Classic Kebab/Gozleme.jpg',12,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Classic Kebab kebab',0,'img/Classic Kebab/Kebab.jpg',13,1);/*20*/
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Classic Kebab pizza',0,'img/Classic Kebab/Pizza.jpg',3,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('CCoco Cubano environment',0,'img/Coco Cubano/2013-09-17 11.29.36.jpg',9,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Scotch Fillet steak with chips and garlic sauce',0,'img/Coco Cubano/Scotch Fillet steak with chips and garlic sauce.jpg',14,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('chips and salad',0,'img/Coco Cubano/chips and salad.jpg',15,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Mini Chicken Chimichangas',0,'img/Guzman Y Gomez/Mini Chicken Chimichangas.jpg',16,1);/*25*/
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Jewel of India from outside',0,'img/Jewel of India/1-1812.jpg',9,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Char Kway Teow',0,'img/Mamak/Char Kway Teow.jpg',17,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Combination Hor Fun',0,'img/Mamak/Combination Hor Fun.jpg',17,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Ice cream float & peanut milkshake',0,'img/Mamak/Ice cream float & peanut milkshake.jpg',18,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Mee Goreng prawns & fish cakes',0,'img/Mamak/Mee Goreng prawns & fish cakes.jpg',17,1);/*30*/
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Nasi Goreng (top) & Nasi Lemak (bottom)',0,'img/Mamak/Nasi Goreng (top) & Nasi Lemak (bottom).jpg',17,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Roti Canai (top pics) & Roti Murtabak (bottom pics)',0,'img/Mamak/Roti Canai (top pics) & Roti Murtabak (bottom pics).jpg',17,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Max Brenner waffle.',0,'img/Max Brenner/maxbrenner1.jpg',23,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Q Lounge from outside',0,'img/Q Lounge/10617182_446279278843451_222983860_n.jpg',9,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('falafels and more',0,'img/Yummba/1490737_756926667668938_1081006206_o.jpg',9,1);/*35*/
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('falafels',0,'img/Yummba/falafels.png',22,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Max Brenner icecream on top.',0,'img/Max Brenner/89a06c02.jpg',18,2);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Max Brenner pancake.',0,'img/Max Brenner/3972042885945978638972615518339015077818551673247560n.jpg',24,2);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Max Brenner chocolate pizza.',0,'img/Max Brenner/chocolatepizza729420x0111.jpg',25,2);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Max Brenner fruits with chocolate.',0,'img/Max Brenner/foodie-central-3.jpg',25,2);/*40*/
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Max Brenner fruits with chocolate.',0,'img/Max Brenner/IMG_8194.jpg',23,2);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Subway from outside.',0,'img/Subway UNSW/SubChickenSchnitzel.jpg',1,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Subway from outside.',0,'img/Subway UNSW/SubPizza.jpg',1,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Subway from outside.',0,'img/Subway UNSW/SubSeafoodSensation.jpg',1,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Subway from outside.',0,'img/Subway UNSW/SubChickenBaconMelt.jpg',1,1);/*45*/
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Subway from outside.',0,'img/Subway UNSW/SubChickenParmigiana.jpg',1,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Subway from outside.',0,'img/Subway UNSW/SubChickenSchnitzel.jpg',1,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Subway from outside.',0,'img/Subway UNSW/SubTurkeyHam.jpg',1,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Subway from outside.',0,'img/Subway UNSW/SubMeatBall.jpg',1,1);
INSERT INTO PHOTOS (INFORMATION,LIKE_,URL,TAG_ID,USER_ID) VALUES ('Subway from outside.',0,'img/Subway UNSW/SubHam.jpg',1,1);

/*restaurant tag*/
INSERT INTO PREFERENCES (PREFERENCE) VALUES ('Fast Food');
INSERT INTO PREFERENCES (PREFERENCE) VALUES ('Asian Food');
INSERT INTO PREFERENCES (PREFERENCE) VALUES ('Mediterranean Food');
INSERT INTO PREFERENCES (PREFERENCE) VALUES ('Coffee shop');
INSERT INTO PREFERENCES (PREFERENCE) VALUES ('Vietnamese Food');/*5*/
INSERT INTO PREFERENCES (PREFERENCE) VALUES ('Cuban Food');
INSERT INTO PREFERENCES (PREFERENCE) VALUES ('Mexican Food');
INSERT INTO PREFERENCES (PREFERENCE) VALUES ('Malaysian Food');
INSERT INTO PREFERENCES (PREFERENCE) VALUES ('Desserts');
INSERT INTO PREFERENCES (PREFERENCE) VALUES ('Vegetarian');/*10*/
INSERT INTO PREFERENCES (PREFERENCE) VALUES ('Miscellaneous');
INSERT INTO PREFERENCES (PREFERENCE) VALUES ('Drinks');
INSERT INTO PREFERENCES (PREFERENCE) VALUES ('Turkish Food');
INSERT INTO PREFERENCES (PREFERENCE) VALUES ('Indian Food');

/*add photo*/
INSERT INTO RESTAURANTS_PHOTOS VALUES (1,1);
INSERT INTO RESTAURANTS_PHOTOS VALUES (42,1);
INSERT INTO RESTAURANTS_PHOTOS VALUES (43,1);
INSERT INTO RESTAURANTS_PHOTOS VALUES (44,1);
INSERT INTO RESTAURANTS_PHOTOS VALUES (45,1);
INSERT INTO RESTAURANTS_PHOTOS VALUES (46,1);
INSERT INTO RESTAURANTS_PHOTOS VALUES (47,1);
INSERT INTO RESTAURANTS_PHOTOS VALUES (48,1);
INSERT INTO RESTAURANTS_PHOTOS VALUES (49,1);
INSERT INTO RESTAURANTS_PHOTOS VALUES (50,1);
INSERT INTO RESTAURANTS_PHOTOS VALUES (2,2);
INSERT INTO RESTAURANTS_PHOTOS VALUES (3,2);
INSERT INTO RESTAURANTS_PHOTOS VALUES (4,2);
INSERT INTO RESTAURANTS_PHOTOS VALUES (33,2);
INSERT INTO RESTAURANTS_PHOTOS VALUES (37,2);
INSERT INTO RESTAURANTS_PHOTOS VALUES (38,2);
INSERT INTO RESTAURANTS_PHOTOS VALUES (39,2);
INSERT INTO RESTAURANTS_PHOTOS VALUES (40,2);
INSERT INTO RESTAURANTS_PHOTOS VALUES (41,2);
INSERT INTO RESTAURANTS_PHOTOS VALUES (5,3);
INSERT INTO RESTAURANTS_PHOTOS VALUES (6,3);
INSERT INTO RESTAURANTS_PHOTOS VALUES (7,3);
INSERT INTO RESTAURANTS_PHOTOS VALUES (8,4);
INSERT INTO RESTAURANTS_PHOTOS VALUES (9,5);
INSERT INTO RESTAURANTS_PHOTOS VALUES (10,5);
INSERT INTO RESTAURANTS_PHOTOS VALUES (11,6);
INSERT INTO RESTAURANTS_PHOTOS VALUES (12,6);
INSERT INTO RESTAURANTS_PHOTOS VALUES (13,6);
INSERT INTO RESTAURANTS_PHOTOS VALUES (14,7);
INSERT INTO RESTAURANTS_PHOTOS VALUES (15,8);
INSERT INTO RESTAURANTS_PHOTOS VALUES (16,9);
INSERT INTO RESTAURANTS_PHOTOS VALUES (17,10);
INSERT INTO RESTAURANTS_PHOTOS VALUES (18,10);
INSERT INTO RESTAURANTS_PHOTOS VALUES (19,10);
INSERT INTO RESTAURANTS_PHOTOS VALUES (20,10);
INSERT INTO RESTAURANTS_PHOTOS VALUES (21,10);
INSERT INTO RESTAURANTS_PHOTOS VALUES (22,11);
INSERT INTO RESTAURANTS_PHOTOS VALUES (23,11);
INSERT INTO RESTAURANTS_PHOTOS VALUES (24,11);
INSERT INTO RESTAURANTS_PHOTOS VALUES (25,12);
INSERT INTO RESTAURANTS_PHOTOS VALUES (26,13);
INSERT INTO RESTAURANTS_PHOTOS VALUES (27,14);
INSERT INTO RESTAURANTS_PHOTOS VALUES (28,14);
INSERT INTO RESTAURANTS_PHOTOS VALUES (29,14);
INSERT INTO RESTAURANTS_PHOTOS VALUES (30,14);
INSERT INTO RESTAURANTS_PHOTOS VALUES (31,14);
INSERT INTO RESTAURANTS_PHOTOS VALUES (32,14);
INSERT INTO RESTAURANTS_PHOTOS VALUES (34,15);
INSERT INTO RESTAURANTS_PHOTOS VALUES (35,16);
INSERT INTO RESTAURANTS_PHOTOS VALUES (36,16);

/*add restaurant*/
INSERT INTO RESTAURANTS_PREFERENCES VALUES (1,1);
INSERT INTO RESTAURANTS_PREFERENCES VALUES (2,9);
INSERT INTO RESTAURANTS_PREFERENCES VALUES (3,3);
INSERT INTO RESTAURANTS_PREFERENCES VALUES (4,4);
INSERT INTO RESTAURANTS_PREFERENCES VALUES (5,2);
INSERT INTO RESTAURANTS_PREFERENCES VALUES (6,2);
INSERT INTO RESTAURANTS_PREFERENCES VALUES (7,11);
INSERT INTO RESTAURANTS_PREFERENCES VALUES (8,12);
INSERT INTO RESTAURANTS_PREFERENCES VALUES (9,5);
INSERT INTO RESTAURANTS_PREFERENCES VALUES (10,13);
INSERT INTO RESTAURANTS_PREFERENCES VALUES (11,6);
INSERT INTO RESTAURANTS_PREFERENCES VALUES (12,7);
INSERT INTO RESTAURANTS_PREFERENCES VALUES (13,14);
INSERT INTO RESTAURANTS_PREFERENCES VALUES (14,8);
INSERT INTO RESTAURANTS_PREFERENCES VALUES (15,4);
INSERT INTO RESTAURANTS_PREFERENCES VALUES (16,13);

/*user preferrence*/
INSERT INTO USERS_PREFERENCES VALUES (1,1);
INSERT INTO USERS_PREFERENCES VALUES (2,2);
INSERT INTO USERS_PREFERENCES VALUES (3,1);
INSERT INTO USERS_PREFERENCES VALUES (3,2);

/*user rating*/
INSERT INTO USER_RATINGS VALUES (1,1,5);
INSERT INTO USER_RATINGS VALUES (2,1,4);
INSERT INTO USER_RATINGS VALUES (3,2,5);
INSERT INTO USER_RATINGS VALUES (1,2,3);
INSERT INTO USER_RATINGS VALUES (2,2,5);
